migrate from drone ci to gh actions
tidy up template

tidy up template

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,6 +1,19 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 #awk is needed by sriov-manage utility from nvidia to perform gpu management
+
 RUN zypper -n install pciutils which curl ethtool awk
+
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
 RUN /sbin/update-pciids
-COPY bin/pcidevices /bin/pcidevices
+COPY bin/pcidevices-${ARCH} /bin/pcidevices
 ENTRYPOINT ["pcidevices"]
